version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: adoptme-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: adoptme-app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - MONGO_URL=mongodb://mongo:27017/adoptme
    depends_on:
      - mongo

volumes:
  mongo_data:
